#!/bin/bash

function createManufacturer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/manufacturer.electronics.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/manufacturer.electronics.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-manufacturer --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-manufacturer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-manufacturer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-manufacturer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-manufacturer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/manufacturer.electronics.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy manufacturer's CA cert to manufacturer's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/manufacturer.electronics.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/manufacturer.electronics.com/msp/tlscacerts/ca.crt"

  # Copy manufacturer's CA cert to manufacturer's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/manufacturer.electronics.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/manufacturer.electronics.com/tlsca/tlsca.manufacturer.electronics.com-cert.pem"

  # Copy manufacturer's CA cert to manufacturer's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/manufacturer.electronics.com/ca"
  cp "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/manufacturer.electronics.com/ca/ca.manufacturer.electronics.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-manufacturer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-manufacturer --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-manufacturer --id.name manufactureradmin --id.secret manufactureradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-manufacturer -M "${PWD}/organizations/peerOrganizations/manufacturer.electronics.com/peers/peer0.manufacturer.electronics.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/manufacturer.electronics.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/manufacturer.electronics.com/peers/peer0.manufacturer.electronics.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-manufacturer -M "${PWD}/organizations/peerOrganizations/manufacturer.electronics.com/peers/peer0.manufacturer.electronics.com/tls" --enrollment.profile tls --csr.hosts peer0.manufacturer.electronics.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/manufacturer.electronics.com/peers/peer0.manufacturer.electronics.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/manufacturer.electronics.com/peers/peer0.manufacturer.electronics.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/manufacturer.electronics.com/peers/peer0.manufacturer.electronics.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/manufacturer.electronics.com/peers/peer0.manufacturer.electronics.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/manufacturer.electronics.com/peers/peer0.manufacturer.electronics.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/manufacturer.electronics.com/peers/peer0.manufacturer.electronics.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-manufacturer -M "${PWD}/organizations/peerOrganizations/manufacturer.electronics.com/users/User1@manufacturer.electronics.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/manufacturer.electronics.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/manufacturer.electronics.com/users/User1@manufacturer.electronics.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://manufactureradmin:manufactureradminpw@localhost:7054 --caname ca-manufacturer -M "${PWD}/organizations/peerOrganizations/manufacturer.electronics.com/users/Admin@manufacturer.electronics.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/manufacturer.electronics.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/manufacturer.electronics.com/users/Admin@manufacturer.electronics.com/msp/config.yaml"
}

function createDealer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/dealer.electronics.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/dealer.electronics.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-dealer --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-dealer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-dealer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-dealer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-dealer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/dealer.electronics.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy dealer's CA cert to dealer's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/dealer.electronics.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/dealer.electronics.com/msp/tlscacerts/ca.crt"

  # Copy dealer's CA cert to dealer's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/dealer.electronics.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/dealer.electronics.com/tlsca/tlsca.dealer.electronics.com-cert.pem"

  # Copy dealer's CA cert to dealer's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/dealer.electronics.com/ca"
  cp "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/dealer.electronics.com/ca/ca.dealer.electronics.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-dealer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-dealer --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-dealer --id.name dealeradmin --id.secret dealeradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-dealer -M "${PWD}/organizations/peerOrganizations/dealer.electronics.com/peers/peer0.dealer.electronics.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/dealer.electronics.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/dealer.electronics.com/peers/peer0.dealer.electronics.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-dealer -M "${PWD}/organizations/peerOrganizations/dealer.electronics.com/peers/peer0.dealer.electronics.com/tls" --enrollment.profile tls --csr.hosts peer0.dealer.electronics.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/dealer.electronics.com/peers/peer0.dealer.electronics.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/dealer.electronics.com/peers/peer0.dealer.electronics.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/dealer.electronics.com/peers/peer0.dealer.electronics.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/dealer.electronics.com/peers/peer0.dealer.electronics.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/dealer.electronics.com/peers/peer0.dealer.electronics.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/dealer.electronics.com/peers/peer0.dealer.electronics.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-dealer -M "${PWD}/organizations/peerOrganizations/dealer.electronics.com/users/User1@dealer.electronics.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/dealer.electronics.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/dealer.electronics.com/users/User1@dealer.electronics.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://dealeradmin:dealeradminpw@localhost:8054 --caname ca-dealer -M "${PWD}/organizations/peerOrganizations/dealer.electronics.com/users/Admin@dealer.electronics.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/dealer.electronics.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/dealer.electronics.com/users/Admin@dealer.electronics.com/msp/config.yaml"
}


function createSupplier() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/supplier.electronics.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/supplier.electronics.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-supplier --tls.certfiles "${PWD}/organizations/fabric-ca/supplier/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-supplier.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-supplier.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-supplier.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-supplier.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/supplier.electronics.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy supplier's CA cert to supplier's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/supplier.electronics.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/supplier/ca-cert.pem" "${PWD}/organizations/peerOrganizations/supplier.electronics.com/msp/tlscacerts/ca.crt"

  # Copy supplier's CA cert to supplier's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/supplier.electronics.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/supplier/ca-cert.pem" "${PWD}/organizations/peerOrganizations/supplier.electronics.com/tlsca/tlsca.supplier.electronics.com-cert.pem"

  # Copy supplier's CA cert to supplier's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/supplier.electronics.com/ca"
  cp "${PWD}/organizations/fabric-ca/supplier/ca-cert.pem" "${PWD}/organizations/peerOrganizations/supplier.electronics.com/ca/ca.supplier.electronics.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-supplier --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/supplier/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-supplier --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/supplier/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-supplier --id.name supplieradmin --id.secret supplieradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/supplier/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-supplier -M "${PWD}/organizations/peerOrganizations/supplier.electronics.com/peers/peer0.supplier.electronics.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/supplier/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/supplier.electronics.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/supplier.electronics.com/peers/peer0.supplier.electronics.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-supplier -M "${PWD}/organizations/peerOrganizations/supplier.electronics.com/peers/peer0.supplier.electronics.com/tls" --enrollment.profile tls --csr.hosts peer0.supplier.electronics.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/supplier/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/supplier.electronics.com/peers/peer0.supplier.electronics.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/supplier.electronics.com/peers/peer0.supplier.electronics.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/supplier.electronics.com/peers/peer0.supplier.electronics.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/supplier.electronics.com/peers/peer0.supplier.electronics.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/supplier.electronics.com/peers/peer0.supplier.electronics.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/supplier.electronics.com/peers/peer0.supplier.electronics.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:11054 --caname ca-supplier -M "${PWD}/organizations/peerOrganizations/supplier.electronics.com/users/User1@supplier.electronics.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/supplier/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/supplier.electronics.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/supplier.electronics.com/users/User1@supplier.electronics.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://supplieradmin:supplieradminpw@localhost:11054 --caname ca-supplier -M "${PWD}/organizations/peerOrganizations/supplier.electronics.com/users/Admin@supplier.electronics.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/supplier/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/supplier.electronics.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/supplier.electronics.com/users/Admin@supplier.electronics.com/msp/config.yaml"
}


function createOrderer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/electronics.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/electronics.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/electronics.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/electronics.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/electronics.com/msp/tlscacerts/tlsca.electronics.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/electronics.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/electronics.com/tlsca/tlsca.electronics.com-cert.pem"

  echo "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/electronics.com/orderers/orderer.electronics.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/electronics.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/electronics.com/orderers/orderer.electronics.com/msp/config.yaml"

  echo "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/electronics.com/orderers/orderer.electronics.com/tls" --enrollment.profile tls --csr.hosts orderer.electronics.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/electronics.com/orderers/orderer.electronics.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/electronics.com/orderers/orderer.electronics.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/electronics.com/orderers/orderer.electronics.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/electronics.com/orderers/orderer.electronics.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/electronics.com/orderers/orderer.electronics.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/electronics.com/orderers/orderer.electronics.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/electronics.com/orderers/orderer.electronics.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/electronics.com/orderers/orderer.electronics.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/electronics.com/orderers/orderer.electronics.com/msp/tlscacerts/tlsca.electronics.com-cert.pem"

  echo "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/electronics.com/users/Admin@electronics.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/electronics.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/electronics.com/users/Admin@electronics.com/msp/config.yaml"
}

createManufacturer
createDealer
createSupplier
createOrderer